### ISSUE TITLE
OJ is raising json parser error

### ISSUE THREAD

**Issue by leosurwiki** [ohler55/oj#584] opened 2020-03-04 19:43 UTC
According https://github.com/aws/aws-sdk-ruby/blob/a99d0abf9e61a0f4b848a60043cc4e8db00c8971/gems/aws-sdk-core/lib/aws-sdk-core/json.rb#L62, AWS core only expect Oj to raise `[Oj::ParseError, EncodingError]`. But it's still raising JSON::ParserError. 
```
$ bundle show oj
.rvm/gems/ruby-2.6.2/gems/oj-3.10.5
2.6.2 :001 > Oj.load("<ServiceUnavailableException/>")
Traceback (most recent call last):
        2: from (irb):1
        1: from (irb):1:in `load'
JSON::ParserError (Empty input () at line 1, column 1 [parse.c:995] in '<ServiceUnavailableException/>)
2.6.2 :002 >
```

**Comment by leosurwiki** [comment] 2020-03-04 20:12
Confirmed 3.3.6 works

**Comment by ohler55** [comment] 2020-03-04 20:20
I'm guessing that AWS core is using Oj by mimicking the JSON gem. There was a bug fix where Oj was emitting a Oj error instead of a JSON error. That was fixed. If the desired behavior is to capture an Oj error then use one of the Oj modes such as strict or custom.

Are you one of the maintainers for the AWS gems?

**Comment by leosurwiki** [comment] 2020-03-04 20:28
Thanks a lot for the prompt response! Your explanation does make sense.
Unfortunately, I'm not the maintainer of AWS core sdk gems. I will probably depends on the buggy version for now since our aws core version(3.62.2) is also far behind the latest. 
A fix on their end is necessary, I will create an issue there.

**Comment by ohler55** [comment] 2020-03-04 21:02
Thanks.

**Comment by mullermp** [comment] 2020-03-05 00:23
@ohler55 Do you know what version the bug was fixed in?

**Comment by ohler55** [comment] 2020-03-05 04:26
I one through the changeling and didn't see it. I'd have to check each release. I think the bottom line is Oj is supposed to mimic the JSON gem when mimicking the JSON gem so the only way forward is to have the AWS gem wait for all the potential errors. I suspect a PR to add that would be accepted. Although I have no idea what the turn around cycle is for that team.

**Comment by mullermp** [comment] 2020-03-05 17:35
I am on the Ruby SDK team! I think the path forward here is to add `JSON::ParserError` to the list of errors that we expect to catch.

**Comment by ohler55** [comment] 2020-03-05 21:20
That would be great, thanks.

**Comment by mullermp** [comment] 2020-03-05 22:24
Before I add this, I wanted to validate it. In the latest version (3.10.5) I'm actually unable to reproduce getting `JSON::ParserError`; I get `Oj::ParseError` which the SDK expects. Any ideas?

```
irb(main):001:0> require 'oj'
=> true
irb(main):002:0> Oj::VERSION
=> "3.10.5"
irb(main):003:0> Oj.load("<ServiceUnavailableException/>")
Traceback (most recent call last):
        5: from /Users/mamuller/.rbenv/versions/2.6.5/bin/irb:23:in `<main>'
        4: from /Users/mamuller/.rbenv/versions/2.6.5/bin/irb:23:in `load'
        3: from /Users/mamuller/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        2: from (irb):3
        1: from (irb):3:in `load'
Oj::ParseError (unexpected character () at line 1, column 1 [parse.c:714])
```

For 3.3.6:

```
irb(main):001:0> require 'oj'
=> true
irb(main):002:0> Oj::VERSION
=> "3.3.6"
irb(main):003:0> Oj.load("<ServiceUnavailableException/>")
Traceback (most recent call last):
        5: from /Users/mamuller/.rbenv/versions/2.6.5/bin/irb:23:in `<main>'
        4: from /Users/mamuller/.rbenv/versions/2.6.5/bin/irb:23:in `load'
        3: from /Users/mamuller/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        2: from (irb):3
        1: from (irb):3:in `load'
Oj::ParseError (unexpected character at line 1, column 1 [parse.c:690])
```

**Comment by ohler55** [comment] 2020-03-06 00:18
I can't tell from just the trace. Oj will emit different exception types depending on the mode. When mimicking the JSON gem in `:combat` mode parse errors should be JSON::ParseError. The conversion from Oj::ParseError to JSON::ParseError happens at the end of the parsing. Are you running in `:combat` mode?

**Comment by leosurwiki** [comment] 2020-03-06 00:49
```
{:indent=>0, :second_precision=>3, :circular=>false, :class_cache=>false, :auto_define=>false, :symbol_keys=>false, :bigdecimal_as_decimal=>false, :use_to_json=>true, :use_to_hash=>false, :use_as_json=>false, :nilnil=>false, :empty_string=>false, :allow_gc=>true, :quirks_mode=>true, :allow_invalid_unicode=>false, :allow_nan=>false, :float_precision=>0, :mode=>:compat, :escape_mode=>:json, :time_format=>:ruby, :bigdecimal_load=>:float, :create_id=>"json_class", :space=>nil, :space_before=>nil, :object_nl=>nil, :array_nl=>nil, :nan=>:raise, :omit_nil=>false, :hash_class=>nil, :array_class=>nil, :ignore=>nil}
```
Our Oj options looks like this, we're in `:compact` mode.

**Comment by ohler55** [comment] 2020-03-06 04:04
To get a JSON::ParserError you need to tell Oj to mimic the JSON gem.

```ruby
irb(main):001:0> Oj.mimic_JSON
=> JSON
irb(main):002:0> Oj.load(%||)
Traceback (most recent call last):
        5: from /Users/ohler/.rbenv/versions/2.7.0/bin/irb:23:in `<main>'
        4: from /Users/ohler/.rbenv/versions/2.7.0/bin/irb:23:in `load'
        3: from /Users/ohler/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/irb-1.2.1/exe/irb:11:in `<top (required)>'
        2: from (irb):2
        1: from (irb):2:in `load'
JSON::ParserError (unexpected character () at line 1, column 1 [parse.c:633] in ')
```

**Comment by mullermp** [comment] 2020-03-06 18:54
In `:compat` mode, I'm seeing `EncodingError` with the latest version. Even when I take @leosurwiki 's options, I also see EncodingError: https://dpaste.org/5hjc

In the SDK, we set these options: https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/aws-sdk-core/json.rb#L42 and we rescue from `EncodingError` already: https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/lib/aws-sdk-core/json.rb#L53

**Comment by ohler55** [comment] 2020-03-06 23:55
Note my last comment. Calling Oj.mimic_JSON first is the way to get the JSON::ParserError.

**Comment by mullermp** [comment] 2020-03-09 16:22
I see. I was looking at an old tab when I wrote that and didn't notice your post. Thanks, I was able to repro. I'll add `JSON::ParserError` to the list of errors that we expect to catch.

**Comment by ohler55** [comment] 2020-03-09 16:35
Super, thanks.

**Comment by mullermp** [comment] 2020-03-09 18:44
@ohler55 One last thing that's confusing to me here - when would someone want to use `mimic_JSON` versus setting `:compat` mode?

When I tried using @leosurwiki 's options exactly, I couldn't reproduce. In the other thread, @leosurwiki mentioned using the `oj_mimic_json` gem. It seems that `mimic_JSON` will trump any other `Oj.default_options = {..}` that we may set.

**Comment by ohler55** [comment] 2020-03-09 18:56
The `oj_mimic_json` gem just calls `Oj.mimic_JSON`. It was made to allow Rails users to just include the gem and not have to write any code.

For people who are using the JSON the `Oj.mimic_JSON` allows them (or should) not have to change their code. Oj then steals the JSON module so JSON.dump is really Oj.dump. If you want to skip the extra machinations with trying to be compatible with the JSON gem then the Oj custom mode is probably your best bet. You will have more direct control but as you can see, it the user forces the mode to be the compat mode that could cause side effects like the changing of raised exception classes.

**Closed** 2020-12-11 00:15 UTC
