### ISSUE TITLE
fetching keys with forward slashes

### ISSUE THREAD

**Issue by vlad43210** [ohler55/oj#324] opened 2016-12-20 15:47 UTC
Hi,

I am trying to figure out how to use Oj::Doc.fetch to get keys with forward slashes in them and I can't get it to work. Here's the code I tested with:

test_hash = {"a/b/c"=>2}
=> {"a/b/c"=>2}
test_json = test_hash.to_json
=> "{\"a/b/c\":2}"
test_doc = Oj::Doc.open(test_json)
=> #<Oj::Doc:0x00000009095958>
test_doc.fetch("['a/b/c']")
=> nil

I used a JSONPath validator and that seems to be a valid JSONPath expression:

JSONPath validator: https://jsonpath.curiousconcept.com/
JSON Data: {"a/b/c":2}
JSONPath expression: ["a/b/c"]
result: [2]

I would really appreciate your help in resolving this issue!

Best,

Vlad

**Comment by ohler55** [comment] 2016-12-20 20:01
Oj::Doc.fetch uses / as the separator character. JSONPath using . as the separator. If you try a.b.c as the field name with JSONPath I'd expect a similar problem. Oj::Doc does over methods for iterating over children that can be used when keys include separator characters.

How would you suggest resolving the issue with breaking existing user code that uses the current / as a separator?

**Comment by vlad43210** [comment] 2016-12-20 21:34
Hi,

I looked at Oj::Doc each_child but do not understand how it works. I tried:

test_hash = {"a/b/c"=>2}
test_json = test_hash.to_json
Oj::Doc.open(test_json) {|doc|
  result = []
  doc.each_child('/a') {|d| result << doc.where? }
  result
}
=> []

I would suggest using an escape sequence, e.g. // or \/, for literal
slashes in keys.

Thanks,

Vlad

**Comment by ohler55** [comment] 2016-12-20 21:39
Try doc.each_child() instead. The /a will nat match anything since there is not child with the name 'a'.

I'll look at what it would take to support escaped / characters in the patterns.

**Comment by vlad43210** [comment] 2016-12-20 22:45
Thanks, looking forward to seeing it!

Vlad

**Comment by ohler55** [comment] 2017-01-09 21:57
Please take a look at the current master on GitHub.

**Comment by vlad43210** [comment] 2017-01-10 03:52
Hi Peter,

I've downloaded the master. I tried adding it to my gemfile as follows:

#in Gemfile
gem 'oj', '2.18.1b1', :path => "path-to-gem"

when I boot up my Sinatra dev environment, I get this error:

racksh

Digest::Digest is deprecated; use Digest

Digest::Digest is deprecated; use Digest

/home/vagrant/projects/oj-master/lib/oj.rb:43:in `require': cannot load
such file -- oj/oj (LoadError)

        from /home/vagrant/projects/oj-master/lib/oj.rb:43:in `<top
(required)>'

        from /usr/local/rvm/gems/ruby-2.1.0@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:76:in
`require'

        from /usr/local/rvm/gems/ruby-2.1.0@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:76:in
`block (2 levels) in require'

        from /usr/local/rvm/gems/ruby-2.1.0@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:72:in
`each'

        from /usr/local/rvm/gems/ruby-2.1.0@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:72:in
`block in require'

        from /usr/local/rvm/gems/ruby-2.1.0@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:61:in
`each'

        from /usr/local/rvm/gems/ruby-2.1.0@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:61:in
`require'

        from /usr/local/rvm/gems/ruby-2.1.0@global/gems/bundler-1.7.6/lib/bundler.rb:133:in
`require'

        from config.ru:4:in `block in <main>'

        from /usr/local/rvm/gems/ruby-2.1.0@sinatra/gems/rack-1.6.5/lib/rack/builder.rb:55:in
`instance_eval'

        from /usr/local/rvm/gems/ruby-2.1.0@sinatra/gems/rack-1.6.5/lib/rack/builder.rb:55:in
`initialize'

        from config.ru:in `new'

        from config.ru:in `<main>'

        from /usr/local/rvm/gems/ruby-2.1.0@sinatra/gems/rack-1.6.5/lib/rack/builder.rb:49:in
`eval'

        from /usr/local/rvm/gems/ruby-2.1.0@sinatra/gems/rack-1.6.5/lib/rack/builder.rb:49:in
`new_from_string'

        from /usr/local/rvm/gems/ruby-2.1.0@sinatra/gems/rack-1.6.5/lib/rack/builder.rb:40:in
`parse_file'

        from /usr/local/rvm/gems/ruby-2.1.0@sinatra/gems/racksh-1.0.0/lib/racksh/init.rb:23:in
`init'

        from /usr/local/rvm/gems/ruby-2.1.0@sinatra/gems/racksh-1.0.0/bin/racksh:19:in
`<top (required)>'

        from /usr/local/rvm/gems/ruby-2.1.0@sinatra/bin/racksh:23:in `load'

        from /usr/local/rvm/gems/ruby-2.1.0@sinatra/bin/racksh:23:in
`<main>'

        from /usr/local/rvm/gems/ruby-2.1.0@sinatra/bin/ruby_executable_hooks:15:in
`eval'

        from /usr/local/rvm/gems/ruby-2.1.0@sinatra/bin/ruby_executable_hooks:15:in
`<main>'


Any thoughts? FWIW, I am running this inside a vagrant virtual machine for
the dev environment. I am using ruby 2.1.0

Thanks,

Vlad

**Comment by ohler55** [comment] 2017-01-10 03:57
You have to checkout or clone the github repo. Then build the gem and install it. Ruby gems is not going to know about something that has not been officially released. If all that sounds too complicated then I can just skip it and do a release and assume it is good enough for you.

**Comment by vlad43210** [comment] 2017-01-10 15:07
Hi Peter,

I see. I didn't do that, but I did update bundler to use the github repo:
gem 'oj', :git => 'git@github.com:ohler55/oj.git'

When I ran bundle install, it showed:

Using oj 2.18.1b1 from git@github.com:ohler55/oj.git (at master)

Although when I check the version afterwards, it says:

gem list oj

*** LOCAL GEMS ***

oj (2.18.0)

I am not sure if that's wrong or not. Anyway, now I can run racksh without
an error, but the new behavior still does not work for me:

>> test_hash = {"a/b"=>2}

=> {"a/b"=>2}

>> test_json = test_hash.to_json

=> "{\"a/b\":2}"

>> test_doc = Oj::Doc.open(test_json)

=> #<Oj::Doc:0x000000027ee968>

>> test_doc.fetch("a\/b")

=> nil

Best,

Vlad

**Comment by ohler55** [comment] 2017-01-10 20:02
Please try 2.18.1b2. I updated the move but missed the fetch.

**Comment by vlad43210** [comment] 2017-01-10 22:33
Still doesn't work:

Using oj 2.18.1b2 (was 2.18.1b1) from git@github.com:ohler55/oj.git (at
master)

>> test_hash = {"a/b"=>2}

=> {"a/b"=>2}

>> test_json = test_hash.to_json

=> "{\"a/b\":2}"

>> test_doc = Oj::Doc.open(test_json)

=> #<Oj::Doc:0x00000002bf2190>

>> test_doc.fetch("a\/b")

=> nil

Vlad

**Comment by ohler55** [comment] 2017-01-11 05:10
I did add a unit test for that. The problem is that the "a\/b" you are using becomes the sequence of [a / b]. What you want is the sequence of [a \ / b]. You get that with either "a\\/b" or 'a\/b'. The single quoted strings are not exxpanded like the double quotes.

**Comment by vlad43210** [comment] 2017-01-11 19:07
I don't quite understand. Am I using the wrong fetch command? Or is my hash
set up not compatibly with the new feature?

(the practical need for this for me is hashes with URL strings, which have
lots of "/" characters).

Vlad

**Comment by ohler55** [comment] 2017-01-11 20:37
Your hash is fine. You need to understand how Ruby string work though. This is what your example should look like. Not it is exactly the same except for the string provided to fetch.

```ruby
irb(main):001:0> test_hash = {"a/b"=>2}
=> {"a/b"=>2}
irb(main):002:0> test_json = Oj.dump(test_hash)
=> "{\"a/b\":2}"
irb(main):003:0> doc = Oj::Doc.open(test_json)
=> #<Oj::Doc:0x00555c6fd3a268>
irb(main):004:0> doc.fetch("a\\/b")
=> 2
```

**Comment by vlad43210** [comment] 2017-01-11 20:40
Ah, I understand -- it's a single vs. double quote issue. OK,
doc.fetch('a\/b') or doc.fetch("a\\/b") both work for me. Thanks for adding
this feature!

Vlad

**Comment by ohler55** [comment] 2017-01-14 02:17
Ok to close?

**Comment by vlad43210** [comment] 2017-01-14 05:27
Yes.

Vlad

**Closed** 2017-01-14 20:42 UTC
