### ISSUE TITLE
segmentation fault : Oj::Doc.open

### ISSUE THREAD

**Issue by noraj** [ohler55/oj#525] opened 2019-01-17 00:51 UTC
oj (3.7.7)

I get a segmentation fault just by using `Doc.open` on a JSON file.

```ruby
require 'oj'
Oj::Doc.open(File.read('/home/shark/Dev/cve_feeds/nvdcve-1.0-2014.json'))
```

or one-line `ruby -e "require 'oj'; Oj::Doc.open(File.read('/home/shark/Dev/cve_feeds/nvdcve-1.0-2014.json'))"`

You can get the JSON file here: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2014.json.zip

crash log: https://pastebin.com/bAyTxZKd

Demo:

[![asciicast](https://asciinema.org/a/wl9Oax97OiR6RHZ4eqz3Aa7Vq.svg)](https://asciinema.org/a/wl9Oax97OiR6RHZ4eqz3Aa7Vq)

PS : In the example I'm using ruby 2.6.0 but the same happened to me with 2.5.3 and 2.4.5.

**Comment by ohler55** [comment] 2019-01-17 01:48
What platform are you using? I just tried on macOS 10.14.1 with no crash.

Interesting way of showing the example.

**Comment by ohler55** [comment] 2019-01-17 01:56
Nevermind, I hadn't updated the machine. I was able to reproduce on macOS. I'll get it fixed.

**Comment by ohler55** [comment] 2019-01-17 17:06
I checked in a fix. It seems the string was either being garbage collected or triggering a GC and collecting some other object that was not guarded well enough.

**Comment by noraj** [comment] 2019-01-17 19:58
The underlying OS was Manjaro.

**Comment by ohler55** [comment] 2019-01-17 20:56
I've wondered about Manjaro but haven't spent the effort to try it on one of my ubuntu machines.

Anyway, please let me know if the fix works for you. If it does I'll release as soon as I get a Windows time fix in.

**Comment by noraj** [comment] 2019-01-18 18:48
@ohler55 Sure I didn't see e0a462927b16febbcfaab6ab53475bf38a33663c.

**Comment by noraj** [comment] 2019-01-18 19:03
```
$ cd /tmp
$ git clone https://github.com/ohler55/oj.git
$ cd oj
$ irb -Ilib -roj
irb(main):001:0> Oj::Doc.open(File.read('/home/shark/Dev/cve_feeds/nvdcve-1.0-2014.json'))
```

I'm still having the same seg fault.

**Comment by ohler55** [comment] 2019-01-21 01:11
I'm not having much success recreating with the latest master branch. I've tried Ubuntu 16.04 and 18.04 as well as two versions of macOS with no failures. 

I just noticed something. You tried `irb -Ilib -roj` yet since Oj is a C extension `irb -Iext -Ilib -roj` is the command that is needed.

**Comment by noraj** [comment] 2019-01-22 00:33
I don't have a crash using `ruby -e "require 'oj'; Oj::Doc.open(File.read('/home/shark/Dev/cve_feeds/nvdcve-1.0-2014.json'))"` with 3.7.8. No more seg fault.

**Closed** 2019-03-13 22:25 UTC
