### ISSUE TITLE
Won't dump DateTime.now

### ISSUE THREAD

**Issue by alxx** [ohler55/oj#332] opened 2017-01-31 21:21 UTC
Oj locks in a strange neverending loop if I ask it to dump `DateTime.now`.
It works for `Time.now` and for `DateTime.yesterday`, but not with `now()`.

```
[41] pry(main)> Oj.dump DateTime.now
^CInterrupt: 
from (pry):55:in `dump'
[42] pry(main)> Oj.dump Time.now
=> "{\"^t\":1485897301.144503000e3600}"
[43] pry(main)> Oj.dump DateTime.yesterday
=> "{\"^O\":\"Date\",\"year\":2017,\"month\":1,\"day\":30,\"start\":2299161.0}"
```

For simplicity, these examples show me trying to dump `DateTime.now` as an atom (admittedly not a very useful thing to do), but the behaviour replicates when `DateTime.now` is anywhere in any structure I'm trying to dump.

This happens with the default options, and I'm using version 2.18.1.

**Comment by ohler55** [comment] 2017-01-31 21:34
I'll look at it later today. Is this by any chance related to the change in the way as_json methods are called? The :use_as_json option was added recently.

**Comment by alxx** [comment] 2017-01-31 22:34
No, this was a simple straightforward Oj.dump call. I don't even know what :use_as_json does.

**Comment by dmvt** [comment] 2017-01-31 22:58
@ohler55 Possibly related:
```ruby
irb(main):001:0> Oj.dump(DateTime.new)
=> "\"-4712-01-01T00:00:00+00:00\""
irb(main):002:0> Oj.dump(Time.new)
=> "\"2017-01-31 17:48:10 -0500\""
irb(main):005:0> Oj.dump Client.first.created_at
  Client Load (0.9ms)  SELECT "accounts".* FROM "accounts" WHERE "accounts"."type" IN ('Client') LIMIT 1
=> "{\"time\":null,\"time_zone\":{\"name\":\"UTC\",\"utc_offset\":null,\"tzinfo\":{\"identifier\":\"Etc/UTC\",\"real_timezone\":{\"info\":{\"identifier\":\"Etc/UTC\",\"offsets\":{\"o0\":{\"utc_offset\":0,\"std_offset\":0,\"abbreviation\":\"UTC\",\"utc_total_offset\":0}},\"transitions\":[],\"previous_offset\":{\"utc_offset\":0,\"std_offset\":0,\"abbreviation\":\"UTC\",\"utc_total_offset\":0},\"transitions_index\":null}}},\"current_period\":null},\"utc\":\"2013-08-13 16:56:45 UTC\",\"period\":null}"
irb(main):006:0> Oj::VERSION
=> "2.18.1"
```

Rolling back to 2.17.5 fixed the issue. Ruby 2.2.2p95, Rails 3.2.21.

**Comment by ohler55** [comment] 2017-02-01 00:49
Just ran the same with just Oj. No issues so I would guess I am missing something. What are the Oj default_options? I see that the irb output starts with 1, the first entry. What argument did you start it with. Basically, what was required on the command. I assume at least -roj.

**Comment by alxx** [comment] 2017-02-01 07:01
Sorry Peter, to which of us are you talking? :)

Here are my default_options:

```
> Oj.default_options
=> {:indent=>0,
 :second_precision=>9,
 :circular=>false,
 :class_cache=>true,
 :auto_define=>false,
 :symbol_keys=>false,
 :bigdecimal_as_decimal=>true,
 :use_to_json=>false,
 :use_as_json=>false,
 :nilnil=>false,
 :allow_gc=>true,
 :quirks_mode=>true,
 :allow_invalid_unicode=>false,
 :float_precision=>15,
 :mode=>:object,
 :escape_mode=>:json,
 :time_format=>:unix_zone,
 :bigdecimal_load=>:auto,
 :create_id=>"json_class",
 :space=>nil,
 :space_before=>nil,
 :object_nl=>nil,
 :array_nl=>nil,
 :nan=>:auto,
 :omit_nil=>false,
 :hash_class=>nil}
```

I've done absolutely nothing but add oj in my Gemfile and then noticed that issue when trying to dump the current DateTime. I'm using pry, not irb, with no arguments, whatever "rails c" feeds into it. I don't know if/that Dan's problem is related.

Speaking of... I can't replicate the problem in a regular pry session. It works fine there. It's only in Rails context that this locks up. And I've noticed that DateTime.now returns different values in a regular pry console, as opposed to the Rails 5.0.0.1 console:

In Rails:

```
pry(main)> DateTime.now
=> Wed, 01 Feb 2017 07:58:41 +0100
```

Generic:

```
pry(main)> DateTime.now
=> #<DateTime: 2017-02-01T07:58:47+01:00 ((2457786j,25127s,363100000n),+3600s,2299161j)>
```

So it might be related to some other gem I use; however, Oj shouldn't probably hang up as it does.

**Comment by dmvt** [comment] 2017-02-01 15:07
I was in the Rails console. Here are my default options:

```
> Oj.default_options
=> {:indent=>0,
 :second_precision=>9,
 :circular=>false,
 :class_cache=>true,
 :auto_define=>false,
 :symbol_keys=>false,
 :bigdecimal_as_decimal=>true,
 :use_to_json=>true,
 :nilnil=>false,
 :allow_gc=>true,
 :quirks_mode=>true,
 :allow_invalid_unicode=>false,
 :float_precision=>15,
 :mode=>:compat,
 :escape_mode=>:json,
 :time_format=>:ruby,
 :bigdecimal_load=>:auto,
 :create_id=>"json_class",
 :space=>nil,
 :space_before=>nil,
 :object_nl=>nil,
 :array_nl=>nil,
 :nan=>:auto,
 :omit_nil=>false,
 :hash_class=>nil}
```

It definitely looks related to Rails, not Ruby. In console, this was only an issue with DateTime fields on the model instances.

**Comment by ohler55** [comment] 2017-02-01 16:57
Odd, I don't see the :use_as_json option. You must have displayed the 2.17.5 version. With rails involved I highly suspect the issue is :use_as_json is false. Change it to true and everything should work as before. The more recent active components prefer as_json() over to_json(). Oj let you pick which of those method are considered. to_json() was notorious for calling itself and getting in an endless loop.

**Comment by dmvt** [comment] 2017-02-01 18:47
Gotcha... ok. I'm not going to upgrade again at this time, but hopefully this will help someone else out.

**Comment by ohler55** [comment] 2017-02-01 20:31
There have been a number of people who missed the new :use_as_json option in the release notes. So far just setting it to true, like the :use_to_json option has solved the problems.

**Comment by alxx** [comment] 2017-02-01 20:38
How about new users, who have no reason to read the CHANGELOG? I don't see :use_as_json documented anywhere to be honest. I still don't know what it does and whether I should use it and what the implications are.

My own fix to the issue was to use `to_s` and then just parse it as DateTime again after Oj.load.

**Comment by ohler55** [comment] 2017-02-01 21:05
http://www.ohler.com/oj/Oj.html#default_options%3D-class_method

The introduction of :use_as_json came about due to users wanting control of the calls to to_json() to be separate from calls to as_json(). That was prompted by rail and active support use. :use_to_json used to control calls to both to_json() and as_json(). Separating them means :use_as_json needs to be true to get the same behavior as 2.17.5 with :use_to_json set to true.

**Comment by ohler55** [comment] 2017-02-10 17:56
Did that take care of the issue?

**Comment by alxx** [comment] 2017-02-10 18:03
Did what take care of it? Since @dmvt joined the thread, I'm not even sure whom you're talking to :)

I'm not about to mess with options I don't understand. I solved my issue by converting the dump parameter to a string and left it there.

As I said, all I'm doing is a simple Oj.dump and I'm not using as_json or anything like that.

**Comment by dmvt** [comment] 2017-02-10 18:25
Hi @ohler55 I'm sure that is the issue for me. Haven't tried `:use_to_json`, but it makes total sense. Thanks for the follow ups!

**Comment by ohler55** [comment] 2017-02-10 18:29
ok, closing then, thanks

**Closed by ohler55** 2017-02-10 18:29 UTC
