### ISSUE TITLE
Verison 3.13.x crashes cmake - error in cache.c

### ISSUE THREAD

**Issue by RemcoVanDerVeen** [ohler55/oj#689] opened 2021-08-10 10:43 UTC
Updating oj to version 3.13.0 resulted in the following error in our deploy cycle. It was not solved by 3.13.1.
Here is the error log:

```
current directory: /usr/local/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/oj-3.13.1/ext/oj
/usr/local/rbenv/versions/2.6.1/bin/ruby -I /usr/local/rbenv/versions/2.6.1/lib/ruby/site_ruby/2.6.0 -r ./siteconf20210810-49232-alhbhg.rb extconf.rb
>>>>> Creating Makefile for ruby version 2.6.1 on x86_64-linux <<<<<
checking for rb_time_timespec()... yes
checking for rb_ivar_count()... yes
checking for rb_ivar_foreach()... yes
checking for rb_gc_mark_movable()... no
checking for stpcpy()... yes
checking for pthread_mutex_init()... yes
checking for rb_enc_associate()... yes
checking for rb_ext_ractor_safe() in ruby.h... no
creating Makefile

current directory: /usr/local/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/oj-3.13.1/ext/oj
make DESTDIR\= clean

current directory: /usr/local/rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/oj-3.13.1/ext/oj
make DESTDIR\=
compiling cache.c
cache.c: In function ‘rehash’:
cache.c:115:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (Slot *sp = c->slots; sp < end; sp++) {
     ^
cache.c:115:5: note: use option -std=c99 or -std=gnu99 to compile your code
cache.c: In function ‘cache_free’:
cache.c:133:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (uint32_t i = 0; i < c->size; i++) {
     ^
cache.c:135:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (Slot s = c->slots[i]; NULL != s; s = next) {
         ^
cache.c: In function ‘cache_mark’:
cache.c:146:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (uint32_t i = 0; i < c->size; i++) {
         ^
cache.c:147:13: error: ‘for’ loop initial declarations are only allowed in C99 mode
             for (Slot s = c->slots[i]; NULL != s; s = s->next) {
             ^
cache.c: At top level:
cc1: warning: unrecognized command line option "-Wno-tautological-compare" [enabled by default]
cc1: warning: unrecognized command line option "-Wno-self-assign" [enabled by default]
cc1: warning: unrecognized command line option "-Wno-parentheses-equality" [enabled by default]
cc1: warning: unrecognized command line option "-Wno-constant-logical-operand" [enabled by default]
cc1: warning: unrecognized command line option "-Wno-cast-function-type" [enabled by default]
make: *** [cache.o] Error 1

make failed, exit code 2
```

**Comment by ohler55** [comment] 2021-08-10 11:36
I suppose I'll have to continue to support old compilers. C99 is 22 years old at this point though. I'll get a fix in probably tomorrow.

**Comment by ohler55** [comment] 2021-08-11 01:29
Please try the c99 branch.

**Comment by andrepiske** [comment] 2021-08-12 08:11
> Can someone verify that the new c99 branch builds on a C99 compiler?

Got a few errors, made adjustments until it compiled. Changes are in #692

**Comment by RemcoVanDerVeen** [comment] 2021-08-12 09:48
> Please try the c99 branch.

I tried it today, but the same error message occurs, unfortunately. I'm trying to find out which C-compiler I'm dealing with, perhaps that might help.

**Comment by randyv12** [comment] 2021-08-13 20:33
for a temp workaround, if anyone gets stuck and you are working on jenkins, you have the option to specify... something.. like this ...
```
bundle config build.oj --with-cflags="-std=gnu99 -Wno-error=implicit-function-declaration"
```
it seems like it builds on gnu99 for uh.. 
Ubuntu 4.8.4-2ubuntu1~14.04.4
:)

**Comment by ohler55** [comment] 2021-08-13 20:50
@RemcoVanDerVeen have you tried the c99 branch after the additional changed made by @andrepiske ?

**Comment by mathieujobin** [comment] 2021-08-16 11:07
I am getting the same error on beanstalk, I will test with the `c99` branch

```
  creating Makefile
  
  current directory: /var/app/ondeck/vendor/bundle/gems/oj-3.13.1/ext/oj
  make DESTDIR\= clean
  
  current directory: /var/app/ondeck/vendor/bundle/gems/oj-3.13.1/ext/oj
  make DESTDIR\=
  compiling cache.c
  cache.c: In function ‘rehash’:
  cache.c:115:5: error: ‘for’ loop initial declarations are only allowed in C99
  mode
       for (Slot *sp = c->slots; sp < end; sp++) {
       ^
  cache.c:115:5: note: use option -std=c99 or -std=gnu99 to compile your code
  cache.c: In function ‘cache_free’:
  cache.c:133:5: error: ‘for’ loop initial declarations are only allowed in C99
  mode
       for (uint32_t i = 0; i < c->size; i++) {
       ^
  cache.c:135:9: error: ‘for’ loop initial declarations are only allowed in C99
  mode
           for (Slot s = c->slots[i]; NULL != s; s = next) {
           ^
  cache.c: In function ‘cache_mark’:
  cache.c:146:9: error: ‘for’ loop initial declarations are only allowed in C99
  mode
           for (uint32_t i = 0; i < c->size; i++) {
           ^
  cache.c:147:13: error: ‘for’ loop initial declarations are only allowed in C99
  mode
               for (Slot s = c->slots[i]; NULL != s; s = s->next) {
               ^
  cache.c: At top level:
  cc1: warning: unrecognized command line option "-Wno-tautological-compare"
  [enabled by default]
  cc1: warning: unrecognized command line option "-Wno-self-assign" [enabled by
  default]
  cc1: warning: unrecognized command line option "-Wno-parentheses-equality"
  [enabled by default]
  cc1: warning: unrecognized command line option "-Wno-constant-logical-operand"
  [enabled by default]
  cc1: warning: unrecognized command line option "-Wno-cast-function-type"
  [enabled by default]
  make: *** [cache.o] Error 1
  
  make failed, exit code 2

  Gem files will remain installed in /var/app/ondeck/vendor/bundle/gems/oj-3.13.1
```

**Comment by mathieujobin** [comment] 2021-08-16 11:23
I confirmed, my issue is fixed with `c99` branch !

**Comment by ohler55** [comment] 2021-08-16 12:04
If no one else has this issue with the c99 branch I'll release tonight.

**Comment by RemcoVanDerVeen** [comment] 2021-08-16 15:01
I tried it today, and the issue is fixed with the new `c99` branch!

**Comment by bheemreddy181** [comment] 2021-08-16 22:35
Waiting for a release

**Comment by ohler55** [comment] 2021-08-16 22:51
Released!

**Comment by ohler55** [comment] 2021-08-27 23:40
Closing as the people involved here seems to be satisfied.

**Closed by ohler55** 2021-08-27 23:40 UTC
