### ISSUE TITLE
oj gem 3.13.15+ causes an illegal instruction on CPUs that do not support SSE4.2

### ISSUE THREAD

**Issue by Supermathie** [ohler55/oj#789] opened 2022-07-14 19:54 UTC
After the introduction of `cmpestri` in a455c389c0bd09cb591d1144e9366fc3f3280da0, people with CPUs that do not support SSE4.2 cannot use the gem.

We have multiple reports of ruby abending with an Illegal Instruction from users of Discourse:

https://meta.discourse.org/t/discourse-update-keeps-failing/231862/25?u=supermathie

https://meta.discourse.org/t/discourse-update-keeps-failing/231862/33?u=supermathie

Can we add a runtime check here to ensure the instruction is supported prior to using it?

**Comment by ohler55** [comment] 2022-07-15 14:50
@Watson1978 can you look into this?

**Comment by Watson1978** [comment] 2022-07-15 19:39
it might be solved by https://github.com/ohler55/oj/pull/791.
if not, it might to need to remove the codes for SSE.

**Comment by ohler55** [comment] 2022-07-15 20:21
@Supermathie can you give the develop branch a try?

**Comment by Supermathie** [comment] 2022-07-21 05:40
I can't, since I don't actually have hardware lacking SSE4.2 support.

But for *us* (and I suspect for others who do the same) this won't work in the long term without additional workarounds and continual awareness of this since we ship a docker image with compiled gems.

A workaround would be having the user compile & install the gem on startup to ensure appropriate SSE4.2 [non]usage. Not ideal, but doable.

**Comment by Watson1978** [comment] 2022-07-21 09:41
If we're going to check at runtime, I think it's better to delete the relevant codes because of the overhead...

**Comment by ohler55** [comment] 2022-07-21 11:15
How about an environment variable that is checked in extconf.rb to block use of SSE4.2?

**Comment by SamSaffron** [comment] 2022-07-21 23:31
> If we're going to check at runtime, I think it's better to delete the relevant codes because of the overhead...

Can't we compile to variants and then at first load of the library fiddle with function pointers so it points at the right place, thus erasing all the runtime overhead and only having this be minor boot time overhead?

**Comment by eduardobonet** [comment] 2022-07-25 09:16
We are also seeing many reports of this upon upgrading to 3.13.16: https://gitlab.com/gitlab-org/gitlab/-/issues/368656

**Comment by ohler55** [comment] 2022-07-25 17:38
@Watson1978 maybe the SSE4.2 code needs to be remove (commented out) until these issue are resolved or maybe just make it a manually activate option if a specific environment variable is set during compile.

**Comment by eduardobonet** [comment] 2022-07-25 20:34
Can it be reverted as mitigation?

**Comment by stanhu** [comment] 2022-07-25 20:46
Note that we build `oj` on a machine that does have SSE 4.2 instructions, but we have a number of users who run on older hardware.

Can we make this a flag that can be explicitly disabled?

**Comment by stanhu** [comment] 2022-07-25 20:49
Alternatively, a runtime check could be used: https://stackoverflow.com/a/29179263/1992201

**Comment by stanhu** [comment] 2022-07-26 17:40
I think we can close this issue. I've received confirmation from users with x86 hardware without SSE instructions that 3.3.18 solves the problem.

I've also verified that 3.3.18 properly enables SSE 4.2 for x86 on Linux and macOS, while leaves it off for macOS `arm64` platforms.

**Closed** 2022-07-26 21:01 UTC

**Comment by stanhu** [comment] 2022-08-02 13:39
I may have spoken too soon. It seems that with the `-msse42` flag, the `.so` contains other SSE instructions that may not be available. Using https://github.com/pkgw/elfx86exts/releases, we see:

```
$ ./elfx86exts /opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/oj-3.13.19/lib/oj/oj.so
MODE64 (call)
CMOV (cmovne)
SSE2 (movq)
SSE41 (pinsrq)
SSE1 (movups)
SSSE3 (pshufb)
SSE3 (movddup)
SSE42 (pcmpestri)
CPU Generation: Unknown
```

Without the `-msse4.2` flag, we get:

```
MODE64 (call)
SSE2 (pxor)
SSE1 (movups)
CMOV (cmovl)
CPU Generation: Intel Core
```

So it seems we may need to have a flag that disables `-msse42` outright here.

**Comment by VojtechMyslivec** [comment] 2022-08-05 14:09
I can confirm that I have encountred:

```
/opt/gitlab/embedded/lib/ruby/gems/2.7.0/gems/oj-3.13.19/lib/oj/oj.so: [BUG] Illegal instruction at 0x00007fb7c5979196
ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-linux]
```

during my gitlab instance upgrade.

I can provide more info about the architecture if needed (it's `qemu` with `kvm` on top of old Intel Xeon 5140).

**Comment by SamSaffron** [comment] 2022-08-08 04:29
We are still a bit worried to update at Discourse. Super hard to test this cause we don't own any hardware with the missing instructions. 

If we are stuck without an easy way to do this in runtime, maybe we skip for now?

**Comment by stanhu** [comment] 2022-08-08 05:45
v3.3.20 is out now and disables this by default: https://github.com/ohler55/oj/pull/806

If you need this optimization, compile the gem with the `--with-sse42` flag.
